# Generated by Django 5.2.6 on 2026-04-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_cf_submission_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
