# Generated by Django 5.2.6 on 2026-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_last_cf_submission_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproblem',
            old_name='attempts',
            new_name='review_priority',
        ),
        migrations.AddField(
            model_name='userproblem',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
