# Generated by Django 5.2.6 on 2026-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_attempts_userproblem_review_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cf_rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cf_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
