# Generated by Django 5.2.6 on 2026-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_cf_rank_userprofile_cf_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_problem',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
